title: "Seeker's Reflections"
description: "Thoughts that pass by"
theme: minima
# User site: leave baseurl empty
baseurl: ""
url: "https://jmak22.github.io"

# Nice-to-haves
paginate: 10
paginate_path: "/page:num"
permalink: /:year/:month/:day/:title/

sass:
  style: compressed
